#!/usr/bin/env python3
# Fix the threshold expression in market_listener.py

file_path = 'D:/leanpython/daily_stock_analysis/paper_trading/market_listener.py'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# The incorrect expression was generated by our earlier script
# Correct form: latest > avg_cost * (threshold_pct/100 + 1)
# Incorrect form: latest > avg_cost * threshold_pct/100 + 1

# Find and fix all occurrences of the pattern with missing parenthesis
import re

# Match: pos.avg_cost * getattr(...) / 100.0 + 1
pattern = r'(pos\.avg_cost \* getattribute\(self,\s*["\']sltp_dynamic_threshold_period["\'],\s*20\.0\s*\)\s*/\s*100\.0\s*\+\s*1)'

# Better approach: just look for the specific line we know has the issue
old_expr = "pos.avg_cost * getattr(self, \"sltp_dynamic_threshold_pct\", 20.0) / 100.0 + 1"
new_expr = "pos.avg_cost * (getattr(self, \"sltp_dynamic_threshold_pct\", 20.0) / 100.0 + 1)"

if old_expr in content:
    content = content.replace(old_expr, new_expr)
    print("[OK] Fixed threshold expression")
else:
    # Try alternative quote styles
    alt_old = "pos.avg_cost * getattr(self, 'sltp_dynamic_threshold_pct', 20.0) / 100.0 + 1"
    if alt_old in content:
        content = content.replace(alt_old, new_expr)
        print("[OK] Fixed threshold expression (single quote variant)")
    else:
        print("[INFO] Expression already correct or not found")

# Also ensure the attribute is set in __init__ with proper config access
# Need to add self.sltp_dynamic_threshold_pct in __init__, getting from config
# Find __init__ method of MarketListener
init_start = content.find('class MarketListener')
if init_start >= 0:
    # Find the __init__ method within this class
    init_method_start = content.find('def __init__', init_start)
    if init_method_start >= 0:
        # Check if the attribute is already being set somewhere in __init__
        init_body = content[init_method_start:init_method_start+1500]
        if 'sltp_dynamic_threshold_pct' not in init_body:
            # Add it near the end of __init__ before the setup code
            # Find where self._... attributes are assigned
            insert_pos = init_method_start + init_body.find('\n        self.')
            if insert_pos > init_method_start:
                # Insert after the first few self assignments
                lines = content[:insert_pos].split('\n')
                for i in range(len(lines)-1, -1, -1):
                    if lines[i].strip().startswith('self.') and '=' in lines[i]:
                        insert_pos = content.find('\n', insert_pos) + 1
                        break
                
                # Insert the new attribute setting
                # We need access to config parameter - typically passed to build_default_listener
                # In MarketListener.__init__, config might be available via self.config or passed differently
                # Let's add a simple default with comment that config should be wired
                attr_line = '\n        # P1-A: dynamic SL/TP threshold percentage (default 20%)\n        self.sltp_dynamic_threshold_pct = 20.0\n'
                content = content[:insert_pos] + attr_line + content[insert_pos:]
                print("[OK] Added sltp_dynamic_threshold_pct attribute to __init__ stub")

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)

print("\nP1-A parametrization complete!")
print("Note: For production, wire the threshold from config in MarketListener.build_default_listener()")